FROM golang:1.16

ARG AUTH_FOLDER_INSIDE_CONTAINER
ARG JSON_KEY_FILENAME
    
WORKDIR /app

COPY . ./
COPY ${JSON_KEY_FILENAME} ${AUTH_FOLDER_INSIDE_CONTAINER}

RUN go mod download

RUN go build -o /pythia
CMD [ "/pythia" ]

